# Generated by Django 4.1 on 2022-09-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_league_alter_team_founded_footballer_team_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="average",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="conseded",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="draw",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="games",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="loss",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="point",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="scored",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="win",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
