# Generated by Django 4.1 on 2022-09-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_team_average_team_conseded_team_draw_team_games_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="average",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="conseded",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="draw",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="games",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="loss",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="point",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="scored",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="win",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
