# Generated by Django 4.1 on 2022-09-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_team_average_alter_team_conseded_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="conseded",
            new_name="conceded",
        ),
    ]
