# Generated by Django 4.1 on 2022-09-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_conseded_team_conceded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="average",
        ),
        migrations.RemoveField(
            model_name="team",
            name="point",
        ),
    ]
