# Generated by Django 4.1 on 2022-09-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_team_average_team_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="average",
        ),
        migrations.RemoveField(
            model_name="team",
            name="point",
        ),
    ]
