# Generated by Django 4.1 on 2022-09-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_team_average_remove_team_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
