# Generated by Django 4.1 on 2022-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_team_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="core/static/images/"
            ),
        ),
    ]
