# Generated by Django 4.1 on 2022-09-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_team_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="image",
        ),
    ]
