# Generated by Django 4.1 on 2022-09-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_team_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(
                blank=True, default="images/Wolves.png", null=True, upload_to="images/"
            ),
        ),
    ]
