# Generated by Django 4.1 on 2022-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_team_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="average",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="point",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
