# Generated by Django 4.1 on 2022-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_team_average_team_point"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["-point", "-average"]},
        ),
        migrations.AddField(
            model_name="league",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
