# Generated by Django 4.1 on 2022-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_team_options_league_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="league",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
