# Generated by Django 4.1 on 2022-10-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_footballer_name_remove_footballer_old_club_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footballer",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Age"),
        ),
    ]
