# Generated by Django 4.1 on 2022-10-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_footballer_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footballer",
            name="age",
        ),
        migrations.RemoveField(
            model_name="footballer",
            name="pos",
        ),
        migrations.AddField(
            model_name="footballer",
            name="position",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="footballer",
            name="player",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
